version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.10
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
# rabbit - user:bitnami
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pass
# mysql - root:pass
volumes:
  rabbitmq_data:
    driver: local